baseURL = "/"
title = "GROW Design & Development"
copyright = "Copyright © 2008–2019, Steve Francia and the Hugo Authors; all rights reserved."
theme = "chunkyPoster"



[menu]
  [[menu.main]]
    identifier = "services"
    name = "Services"
    url = "/services/"
    weight = 1
  [[menu.main]]
    identifier = "portfolio"
    name = "Portfolio"
    url = "/portfolio/"
    weight = 2
  [[menu.main]]
    identifier = "company"
    name = "Company"
    url = "/company/"
    weight = 3
  [[menu.main]]
    identifier = "careers"
    name = "Careers"
    url = "/careers/"
    weight = 4
  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/blog/"
    weight = 5













[taxonomies]
category = "categories"
tag = "tags"
series = "series"
author = "authors"
